version: "3"

services:
  node:
    build: ./backend
    depends_on:
      - sql
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=sql
    ports:
      - 8080:4200
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  sql:
    build: ./sql
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - compose-lesson:/var/lib/mysql
    ports:
      - 33006:3306
  app:
    build: ./frontend
    depends_on:
      - node
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/public:/usr/share/nginx/html
volumes:
  compose-lesson: {}
